using System.Linq;
using GProtobuf.Generator.V2.CodeGeneration.Core;
using GProtobuf.Generator.V2.Handlers;
using GProtobuf.Generator.V2.Handlers.Core;
using GProtobuf.Generator.V2.Handlers.VirtualTypes;
using GProtobuf.Generator.V2.Helpers;

namespace GProtobuf.Generator.V2.CodeGeneration
{
    /// <summary>
    /// Generates a shared file containing all virtual types (MapEntry, Tuple, Collection).
    /// This eliminates code duplication by generating virtual types once in a dedicated namespace
    /// instead of duplicating them in each namespace file.
    /// </summary>
    /// <remarks>
    /// Output: GProtobuf.VirtualTypes.Serialization.cs
    /// Contains: SpanReaders, StreamReaders, SizeCalculators, StreamWriters, BufferWriters,
    ///           StackBufferWriters, OnePassStreamWriters classes with all virtual type methods.
    /// </remarks>
    internal class SharedVirtualTypesGenerator
    {
        public const string SharedNamespace = "GProtobuf.VirtualTypes.Serialization";
        public const string FileName = "GProtobuf.VirtualTypes.Serialization.cs";

        private readonly TypeRegistry _typeRegistry;
        private readonly GeneratorOptions _options;

        public SharedVirtualTypesGenerator(TypeRegistry typeRegistry, GeneratorOptions options)
        {
            _typeRegistry = typeRegistry;
            _options = options ?? GeneratorOptions.Default;
        }

        /// <summary>
        /// Generates the shared virtual types file.
        /// </summary>
        public (string FileName, string FileCode) Generate(
            VirtualMapTypeRegistry mapRegistry,
            VirtualTupleTypeRegistry tupleRegistry)
        {
            var sb = new StringBuilderWithIndent();

            WriteHeader(sb);

            // Generate SpanReaders class
            if (_options.GenerateSpanReader)
            {
                GenerateSpanReadersClass(sb, mapRegistry, tupleRegistry);
            }

            // Generate StreamReaders class
            if (_options.GenerateStreamReader)
            {
                GenerateStreamReadersClass(sb, mapRegistry, tupleRegistry);
            }

            // Generate SizeCalculators class (needed by writers except OnePass)
            if (_options.GenerateStreamWriter || _options.GenerateBufferWriter || _options.GenerateStackBufferWriter)
            {
                GenerateSizeCalculatorsClass(sb, mapRegistry, tupleRegistry);
            }

            // Generate StreamWriters class
            if (_options.GenerateStreamWriter)
            {
                GenerateWritersClass(sb, mapRegistry, tupleRegistry, "Stream", "StreamWriters");
            }

            // Generate BufferWriters class
            if (_options.GenerateBufferWriter)
            {
                GenerateWritersClass(sb, mapRegistry, tupleRegistry, "Buffer", "BufferWriters");
            }

            // Generate StackBufferWriters class
            if (_options.GenerateStackBufferWriter)
            {
                GenerateWritersClass(sb, mapRegistry, tupleRegistry, "StackBuffer", "StackBufferWriters");
            }

            // Generate OnePassStreamWriters class
            if (_options.GenerateOnePassStreamWriter)
            {
                GenerateOnePassStreamWritersClass(sb, mapRegistry, tupleRegistry);
            }

            WriteFooter(sb);

            return (FileName, sb.ToString());
        }

        #region Header/Footer

        private void WriteHeader(StringBuilderWithIndent sb)
        {
            sb.AppendIndentedLine("// <auto-generated>");
            sb.AppendIndentedLine("// This file was generated by GProtobuf Source Generator.");
            sb.AppendIndentedLine("// Contains shared virtual types (MapEntry, Tuple) to eliminate code duplication.");
            sb.AppendIndentedLine("// </auto-generated>");
            sb.AppendIndentedLine("#nullable enable");
            sb.AppendNewLine();
            sb.AppendIndentedLine("using GProtobuf.Core;");
            sb.AppendIndentedLine("using System;");
            sb.AppendIndentedLine("using System.Collections.Generic;");
            sb.AppendIndentedLine("using System.Linq;");
            sb.AppendIndentedLine("using System.IO;");
            sb.AppendIndentedLine("using System.Buffers;");
            sb.AppendIndentedLine("using System.Text;");
            sb.AppendNewLine();
            sb.AppendIndentedLine($"namespace {SharedNamespace}");
            sb.StartNewBlock();
        }

        private void WriteFooter(StringBuilderWithIndent sb)
        {
            sb.EndBlock();
        }

        #endregion

        #region SpanReaders

        private void GenerateSpanReadersClass(StringBuilderWithIndent sb, VirtualMapTypeRegistry mapRegistry, VirtualTupleTypeRegistry tupleRegistry)
        {
            var mapTypes = mapRegistry.GetAllTypes();
            var tupleTypes = tupleRegistry.GetAllTypes();

            if (mapTypes.Count == 0 && tupleTypes.Count == 0)
                return;

            sb.AppendIndentedLine("internal static class SpanReaders");
            sb.StartNewBlock();

            // Generate EstimateMapCapacity helper (if we have any map types)
            if (mapTypes.Count > 0)
            {
                var generator = new VirtualMapEntryGenerator(sb, mapRegistry, _typeRegistry, "Span");

                sb.AppendIndentedLine("#region Map Capacity Estimation");
                sb.AppendNewLine();
                generator.GenerateEstimateMapCapacityHelper();
                sb.AppendIndentedLine("#endregion");
                sb.AppendNewLine();

                // Generate map entry readers
                sb.AppendIndentedLine("// Virtual Map Entry Readers");
                sb.AppendNewLine();

                foreach (var mapType in mapTypes)
                {
                    generator.GenerateReader(mapType);
                }
            }

            // Generate tuple readers
            if (tupleTypes.Count > 0)
            {
                sb.AppendNewLine();
                sb.AppendIndentedLine("// Virtual Tuple Readers");
                sb.AppendNewLine();

                var tupleGenerator = new VirtualTupleGenerator(sb, null, _typeRegistry);
                foreach (var tupleType in tupleTypes)
                {
                    tupleGenerator.GenerateReader(tupleType);
                }
            }

            sb.EndBlock();
            sb.AppendNewLine();
        }

        #endregion

        #region StreamReaders

        private void GenerateStreamReadersClass(StringBuilderWithIndent sb, VirtualMapTypeRegistry mapRegistry, VirtualTupleTypeRegistry tupleRegistry)
        {
            var mapTypes = mapRegistry.GetAllTypes();
            var tupleTypes = tupleRegistry.GetAllTypes();
            var collectionTypes = mapRegistry.GetAllCollectionTypes();

            if (mapTypes.Count == 0 && tupleTypes.Count == 0 && collectionTypes.Count == 0)
                return;

            sb.AppendIndentedLine("internal static class StreamReaders");
            sb.StartNewBlock();

            // Generate map entry readers
            if (mapTypes.Count > 0)
            {
                sb.AppendIndentedLine("// Virtual Map Entry StreamReaders");
                sb.AppendNewLine();

                var generator = new VirtualMapEntryGenerator(sb, mapRegistry, _typeRegistry);
                foreach (var mapType in mapTypes)
                {
                    generator.GenerateStreamReader(mapType);
                }
            }

            // Generate tuple readers
            if (tupleTypes.Count > 0)
            {
                sb.AppendNewLine();
                sb.AppendIndentedLine("// Virtual Tuple StreamReaders");
                sb.AppendNewLine();

                var tupleGenerator = new VirtualTupleGenerator(sb, "Stream", _typeRegistry);
                foreach (var tupleType in tupleTypes)
                {
                    tupleGenerator.GenerateStreamReader(tupleType);
                }
            }

            // Generate collection readers (List, HashSet, Dictionary, Array as nested types in maps)
            if (collectionTypes.Count > 0)
            {
                sb.AppendNewLine();
                sb.AppendIndentedLine("// Virtual Collection StreamReaders");
                sb.AppendNewLine();

                foreach (var collection in collectionTypes)
                {
                    GenerateCollectionReader(sb, collection, mapRegistry);
                }
            }

            sb.EndBlock();
            sb.AppendNewLine();
        }

        private void GenerateCollectionReader(StringBuilderWithIndent sb, VirtualCollectionInfo collection, VirtualMapTypeRegistry mapRegistry)
        {
            switch (collection.Kind)
            {
                case VirtualCollectionKind.List:
                    GenerateListReader(sb, collection, mapRegistry);
                    break;
                case VirtualCollectionKind.HashSet:
                    GenerateHashSetReader(sb, collection, mapRegistry);
                    break;
                case VirtualCollectionKind.Dictionary:
                    GenerateDictionaryReader(sb, collection, mapRegistry);
                    break;
                case VirtualCollectionKind.Array:
                    GenerateArrayReader(sb, collection, mapRegistry);
                    break;
            }
        }

        private void GenerateListReader(StringBuilderWithIndent sb, VirtualCollectionInfo collection, VirtualMapTypeRegistry mapRegistry)
        {
            var elementType = TypeMapping.GetShortTypeName(collection.ElementType);
            var normalizedElementType = TypeMapping.NormalizeTypeName(collection.ElementType);

            // Check if this is a custom collection type (not standard List<T>)
            var isCustomType = !collection.FullTypeName.StartsWith("System.Collections.Generic.List<");
            var returnType = isCustomType
                ? $"global::{collection.FullTypeName}"
                : $"global::System.Collections.Generic.List<{elementType}>";

            sb.AppendIndentedLine($"public static {returnType} Read{collection.SafeName}Content(ref global::GProtobuf.Core.StreamReader reader)");
            sb.StartNewBlock();
            sb.AppendIndentedLine($"var result = new {returnType}();");
            sb.AppendIndentedLine("while (!reader.IsEnd)");
            sb.StartNewBlock();

            GenerateCollectionElementRead(sb, "result", collection.ElementType, collection.ElementTypeInfo, normalizedElementType, mapRegistry);

            sb.EndBlock();
            sb.AppendIndentedLine("return result;");
            sb.EndBlock();
            sb.AppendNewLine();
        }

        private void GenerateHashSetReader(StringBuilderWithIndent sb, VirtualCollectionInfo collection, VirtualMapTypeRegistry mapRegistry)
        {
            var elementType = TypeMapping.GetShortTypeName(collection.ElementType);
            var normalizedElementType = TypeMapping.NormalizeTypeName(collection.ElementType);

            // Check if this is a custom collection type (not standard HashSet<T>)
            var isCustomType = !collection.FullTypeName.StartsWith("System.Collections.Generic.HashSet<");
            var returnType = isCustomType
                ? $"global::{collection.FullTypeName}"
                : $"global::System.Collections.Generic.HashSet<{elementType}>";

            sb.AppendIndentedLine($"public static {returnType} Read{collection.SafeName}Content(ref global::GProtobuf.Core.StreamReader reader)");
            sb.StartNewBlock();
            sb.AppendIndentedLine($"var result = new {returnType}();");
            sb.AppendIndentedLine("while (!reader.IsEnd)");
            sb.StartNewBlock();

            GenerateCollectionElementRead(sb, "result", collection.ElementType, collection.ElementTypeInfo, normalizedElementType, mapRegistry);

            sb.EndBlock();
            sb.AppendIndentedLine("return result;");
            sb.EndBlock();
            sb.AppendNewLine();
        }

        private void GenerateDictionaryReader(StringBuilderWithIndent sb, VirtualCollectionInfo collection, VirtualMapTypeRegistry mapRegistry)
        {
            var keyType = TypeMapping.GetShortTypeName(collection.DictionaryKeyType);
            var valueType = TypeMapping.GetShortTypeName(collection.DictionaryValueType);
            var mapEntryTypeName = VirtualTypeNameGenerator.GetMapEntryTypeName(collection.DictionaryKeyType, collection.DictionaryValueType);

            sb.AppendIndentedLine($"public static global::System.Collections.Generic.Dictionary<{keyType}, {valueType}> Read{collection.SafeName}Content(ref global::GProtobuf.Core.StreamReader reader)");
            sb.StartNewBlock();
            sb.AppendIndentedLine($"var result = new global::System.Collections.Generic.Dictionary<{keyType}, {valueType}>();");
            sb.AppendIndentedLine("while (!reader.IsEnd)");
            sb.StartNewBlock();
            sb.AppendIndentedLine("reader.ReadWireTypeAndFieldId(out var wireType, out var fieldId);");
            sb.AppendIndentedLine($"var entry = StreamReaders.Read{mapEntryTypeName}(ref reader);");
            sb.AppendIndentedLine("if (entry.success)");
            sb.StartNewBlock();
            sb.AppendIndentedLine("result[entry.key] = entry.value;");
            sb.EndBlock();
            sb.EndBlock();
            sb.AppendIndentedLine("return result;");
            sb.EndBlock();
            sb.AppendNewLine();
        }

        private void GenerateArrayReader(StringBuilderWithIndent sb, VirtualCollectionInfo collection, VirtualMapTypeRegistry mapRegistry)
        {
            var elementType = TypeMapping.GetShortTypeName(collection.ElementType);
            var normalizedElementType = TypeMapping.NormalizeTypeName(collection.ElementType);

            sb.AppendIndentedLine($"public static {elementType}[] Read{collection.SafeName}Content(ref global::GProtobuf.Core.StreamReader reader)");
            sb.StartNewBlock();
            sb.AppendIndentedLine($"var tempList = new global::System.Collections.Generic.List<{elementType}>();");
            sb.AppendIndentedLine("while (!reader.IsEnd)");
            sb.StartNewBlock();

            GenerateCollectionElementRead(sb, "tempList", collection.ElementType, collection.ElementTypeInfo, normalizedElementType, mapRegistry);

            sb.EndBlock();
            sb.AppendIndentedLine("return tempList.ToArray();");
            sb.EndBlock();
            sb.AppendNewLine();
        }

        private void GenerateCollectionElementRead(StringBuilderWithIndent sb, string targetVar, string elementType, TypeAnalysisInfo elementTypeInfo, string normalizedElementType, VirtualMapTypeRegistry mapRegistry)
        {
            sb.AppendIndentedLine("reader.ReadWireTypeAndFieldId(out var wireType, out var fieldId);");

            // Check if element is a primitive
            var readExpr = TypeMapping.GetReadExpression(normalizedElementType, DataFormat.Default, "reader", "wireType");
            if (readExpr != null)
            {
                sb.AppendIndentedLine($"{targetVar}.Add({readExpr});");
                return;
            }

            // Check if element is a dictionary
            if (elementTypeInfo?.IsDictionary == true)
            {
                var mapEntryTypeName = VirtualTypeNameGenerator.GetMapEntryTypeName(elementTypeInfo.DictionaryKeyType, elementTypeInfo.DictionaryValueType);
                var keyType = TypeMapping.GetShortTypeName(elementTypeInfo.DictionaryKeyType);
                var valueType = TypeMapping.GetShortTypeName(elementTypeInfo.DictionaryValueType);

                sb.AppendIndentedLine("var entryLength = reader.ReadVarUInt32();");
                sb.AppendIndentedLine("var entryOldLimit = reader.PushLimit((int)entryLength);");
                sb.AppendIndentedLine($"var nestedDict = new global::System.Collections.Generic.Dictionary<{keyType}, {valueType}>();");
                sb.AppendIndentedLine("while (!reader.IsEnd)");
                sb.StartNewBlock();
                sb.AppendIndentedLine("reader.ReadWireTypeAndFieldId(out var _, out var _);");
                sb.AppendIndentedLine($"var entry = StreamReaders.Read{mapEntryTypeName}(ref reader);");
                sb.AppendIndentedLine("if (entry.success) nestedDict[entry.key] = entry.value;");
                sb.EndBlock();
                sb.AppendIndentedLine("reader.PopLimit(entryOldLimit);");
                sb.AppendIndentedLine($"{targetVar}.Add(nestedDict);");
                return;
            }

            // Check if element is a tuple
            if (TupleHandler.IsTupleType(elementType))
            {
                var safeName = TypeNameHelper.GetSafeMethodName(elementType);
                sb.AppendIndentedLine("var itemLength = reader.ReadVarUInt32();");
                sb.AppendIndentedLine("var itemOldLimit = reader.PushLimit((int)itemLength);");
                sb.AppendIndentedLine($"var item = StreamReaders.Read{safeName}Content(ref reader);");
                sb.AppendIndentedLine("reader.PopLimit(itemOldLimit);");
                sb.AppendIndentedLine($"{targetVar}.Add(item);");
                return;
            }

            // Check if element is an enum
            if (elementTypeInfo?.IsEnum == true || _typeRegistry?.IsEnum(elementType) == true || _typeRegistry?.IsEnum(normalizedElementType) == true)
            {
                var shortElementType = TypeMapping.GetShortTypeName(elementType);
                sb.AppendIndentedLine($"{targetVar}.Add((global::{elementType})reader.ReadVarInt32());");
                return;
            }

            // Custom class type
            var className = TypeNameHelper.GetClassName(elementType);
            var readersClass = NamespaceHelper.GetStreamReadersClass(elementType, _typeRegistry);
            sb.AppendIndentedLine("var itemLength = reader.ReadVarUInt32();");
            sb.AppendIndentedLine("var itemOldLimit = reader.PushLimit((int)itemLength);");
            sb.AppendIndentedLine($"var item = {readersClass}.Read{className}Content(ref reader);");
            sb.AppendIndentedLine("reader.PopLimit(itemOldLimit);");
            sb.AppendIndentedLine($"{targetVar}.Add(item);");
        }

        #endregion

        #region SizeCalculators

        private void GenerateSizeCalculatorsClass(StringBuilderWithIndent sb, VirtualMapTypeRegistry mapRegistry, VirtualTupleTypeRegistry tupleRegistry)
        {
            var mapTypes = mapRegistry.GetAllTypes();
            var tupleTypes = tupleRegistry.GetAllTypes();

            if (mapTypes.Count == 0 && tupleTypes.Count == 0)
                return;

            sb.AppendIndentedLine("internal static class SizeCalculators");
            sb.StartNewBlock();

            // Generate map entry size calculators
            if (mapTypes.Count > 0)
            {
                sb.AppendIndentedLine("// Virtual Map Entry Size Calculators");
                sb.AppendNewLine();

                var generator = new VirtualMapEntryGenerator(sb, mapRegistry, _typeRegistry);
                foreach (var mapType in mapTypes)
                {
                    generator.GenerateSizeCalculator(mapType);
                }
            }

            // Generate tuple size calculators
            if (tupleTypes.Count > 0)
            {
                sb.AppendNewLine();
                sb.AppendIndentedLine("// Virtual Tuple Size Calculators");
                sb.AppendNewLine();

                var tupleGenerator = new VirtualTupleGenerator(sb, null, _typeRegistry);
                foreach (var tupleType in tupleTypes)
                {
                    tupleGenerator.GenerateSizeCalculator(tupleType);
                }
            }

            sb.EndBlock();
            sb.AppendNewLine();
        }

        #endregion

        #region Writers (Stream, Buffer, StackBuffer)

        private void GenerateWritersClass(StringBuilderWithIndent sb, VirtualMapTypeRegistry mapRegistry, VirtualTupleTypeRegistry tupleRegistry, string writerKind, string className)
        {
            var mapTypes = mapRegistry.GetAllTypes();
            var tupleTypes = tupleRegistry.GetAllTypes();

            if (mapTypes.Count == 0 && tupleTypes.Count == 0)
                return;

            sb.AppendIndentedLine($"internal static class {className}");
            sb.StartNewBlock();

            // Generate map entry writers
            if (mapTypes.Count > 0)
            {
                sb.AppendIndentedLine($"// Virtual Map Entry {className}");
                sb.AppendNewLine();

                var generator = new VirtualMapEntryGenerator(sb, mapRegistry, _typeRegistry, writerKind);
                foreach (var mapType in mapTypes)
                {
                    generator.GenerateWriter(mapType);
                }
            }

            // Generate tuple writers
            if (tupleTypes.Count > 0)
            {
                sb.AppendNewLine();
                sb.AppendIndentedLine($"// Virtual Tuple {className}");
                sb.AppendNewLine();

                var tupleGenerator = new VirtualTupleGenerator(sb, writerKind, _typeRegistry);
                foreach (var tupleType in tupleTypes)
                {
                    tupleGenerator.GenerateWriter(tupleType);
                }
            }

            sb.EndBlock();
            sb.AppendNewLine();
        }

        #endregion

        #region OnePassStreamWriters

        private void GenerateOnePassStreamWritersClass(StringBuilderWithIndent sb, VirtualMapTypeRegistry mapRegistry, VirtualTupleTypeRegistry tupleRegistry)
        {
            var mapTypes = mapRegistry.GetAllTypes();
            var tupleTypes = tupleRegistry.GetAllTypes();

            if (mapTypes.Count == 0 && tupleTypes.Count == 0)
                return;

            sb.AppendIndentedLine("internal static class OnePassStreamWriters");
            sb.StartNewBlock();

            // Generate map entry writers
            if (mapTypes.Count > 0)
            {
                sb.AppendIndentedLine("// Virtual Map Entry OnePassStreamWriters");
                sb.AppendNewLine();

                var generator = new VirtualMapEntryGenerator(sb, mapRegistry, _typeRegistry, "OnePassStream");
                foreach (var mapType in mapTypes)
                {
                    generator.GenerateWriter(mapType);
                }
            }

            // Generate tuple writers
            if (tupleTypes.Count > 0)
            {
                sb.AppendNewLine();
                sb.AppendIndentedLine("// Virtual Tuple OnePassStreamWriters");
                sb.AppendNewLine();

                var tupleGenerator = new VirtualTupleGenerator(sb, "OnePassStream", _typeRegistry);
                foreach (var tupleType in tupleTypes)
                {
                    tupleGenerator.GenerateWriter(tupleType);
                }
            }

            sb.EndBlock();
            sb.AppendNewLine();
        }

        #endregion
    }
}
