using System.Collections.Generic;

namespace GProtobuf.Generator;

internal static partial class CodeGenerator
{
    private static string GenerateBufferWriterClass(
        string namespaceName,
        IReadOnlyList<TypeDefinition> types,
        RefactoredObjectTree tree)
    {
        var sb = new StringBuilderWithIndent();

        sb.AppendMultiline(
                $"""
                 // <auto-generated/>
                 using GProtobuf.Core;
                 using {namespaceName}.SizeCalculation;
                 using System;
                 using System.Collections.Generic;
                 using System.IO;
                 using System.Buffers;
                 using System.Text;

                 namespace {namespaceName}.Writers
                 """
            )
            .StartNewBlock();

        GenerateWriters(sb, tree, types, WriteTarget.BufferWriter);

        sb.EndBlock();

        return sb.ToString();
    }
}