using System.Collections.Generic;

namespace GProtobuf.Generator;

internal static partial class CodeGenerator
{
    private static string GenerateDeserializerClass(string namespaceName, IReadOnlyList<TypeDefinition> types)
    {
        var sb = new StringBuilderWithIndent();

        sb.AppendMultiline(
            $"""
             // <auto-generated/>
             using GProtobuf.Core;
             using {namespaceName}.Readers;
             using System;
             using System.Collections.Generic;
             using System.IO;
             using System.Buffers;
             using System.Text;

             namespace {namespaceName}.Serialization
             """
        )
            .StartNewBlock()
            .AppendIndentedLine("public static class Deserializers")
            .StartNewBlock();

        foreach (var type in types)
        {
            var className = GetClassNameFromFullName(type.FullName);
            sb.AppendIndentedLine($"public static global::{type.FullName} Deserialize{className}(ReadOnlySpan<byte> data)")
                .StartNewBlock()
                .AppendIndentedLine("var reader = new SpanReader(data);")
                .AppendIndentedLine($"return Readers.SpanReaders.Read{className}(ref reader);")
                .EndBlock()
                .AppendNewLine();
        }

        sb.EndBlock()
            .EndBlock();
        
        return sb.ToString();
    }
}