using System.Collections.Generic;

namespace GProtobuf.Generator;

internal static partial class CodeGenerator
{
    private static string GenerateSerializerClass(string namespaceName, IReadOnlyList<TypeDefinition> types)
    {
        var sb = new StringBuilderWithIndent();
        
        sb.AppendMultiline(
                $"""
                 // <auto-generated/>
                 using GProtobuf.Core;
                 using {namespaceName}.Writers;
                 using System;
                 using System.Collections.Generic;
                 using System.IO;
                 using System.Buffers;
                 using System.Text;

                 namespace {namespaceName}.Serialization
                 """
            )
            .StartNewBlock()
            .AppendIndentedLine("public static class Serializers")
            .StartNewBlock();

        foreach (var type in types)
        {
            var className = GetClassNameFromFullName(type.FullName);
            
            sb.AppendIndentedLine($"public static void Serialize{className}(Stream stream, global::{type.FullName} obj)")
                .StartNewBlock()
                .AppendIndentedLine("var writer = new global::GProtobuf.Core.StreamWriter(stream, stackalloc byte[256]);")
                .AppendIndentedLine($"Writers.StreamWriters.Write{className}(ref writer, obj);")
                .AppendIndentedLine("writer.Flush();")
                .EndBlock()
                .AppendNewLine();
        }

        foreach (var type in types)
        {
            var className = GetClassNameFromFullName(type.FullName);

            sb.AppendIndentedLine($"public static void Serialize{className}(IBufferWriter<byte> buffer, global::{type.FullName} obj)")
                .StartNewBlock()
                .AppendIndentedLine("var writer = new global::GProtobuf.Core.BufferWriter(buffer);")
                .AppendIndentedLine($"Writers.BufferWriters.Write{className}(ref writer, obj);")
                .AppendIndentedLine("writer.Flush();")
                .EndBlock()
                .AppendNewLine();
        }

        sb.EndBlock()
            .EndBlock();

        return sb.ToString();
    }
}