using System.Collections.Generic;
using System.Linq;

namespace GProtobuf.Generator;

internal static partial class CodeGenerator
{
    private static string GenerateSizeCalculatorClass(
        string namespaceName,
        IReadOnlyList<TypeDefinition> types,
        RefactoredObjectTree tree)
    {
        var sb = new StringBuilderWithIndent();

        sb.AppendMultiline(
                $"""
                 // <auto-generated/>
                 using GProtobuf.Core;
                 using System;
                 using System.Collections.Generic;
                 using System.IO;
                 using System.Buffers;
                 using System.Text;

                 namespace {namespaceName}.SizeCalculation
                 """
            )
            .StartNewBlock()
            .AppendIndentedLine("public static class SizeCalculators")
            .StartNewBlock();

        foreach (var type in types)
        {
            var className = GetClassNameFromFullName(type.FullName);
            var containsBaseClass = tree.HasBaseClass(type.FullName);
            if (!containsBaseClass)
            {
                continue;
            }
            
            tree.TryGetBaseClassName(type.FullName, out var baseClassName);
            var baseType = FindTypeByFullName(baseClassName, tree);
            var protoInclude = baseType?.ProtoIncludes.FirstOrDefault(x => x.Type == type.FullName);
            if (protoInclude is null)
            {
                continue;
            }
            
            sb.AppendIndentedLine($"public static void Add{className}ContentSize(ref global::GProtobuf.Core.WriteSizeCalculator calculator, global::{type.FullName} instance)")
                .StartNewBlock();

            var derivedClasses = tree.GetDerivedClasses(type.FullName);
            foreach (var derivedClass in derivedClasses)
            {
                var derivedClassName = GetClassNameFromFullName(derivedClass);
                sb.AppendIndentedLine($"if (instance is global::{derivedClass})")
                    .StartNewBlock();

                WritePrecomputedTagForCalculatorWithName(sb, "calculator", protoInclude.FieldId, WireType.Len);
                    
                sb.AppendMultiline(
                        $"""
                        var calculator{derivedClassName} = new global::GProtobuf.Core.WriteSizeCalculator();
                        SizeCalculators.Calculate{derivedClassName}ContentSize(ref calculator{derivedClassName}, (global::{derivedClass})instance);
                        calculator.WriteVarUInt32((uint)calculator{derivedClassName}.Length);
                        calculator.AddByteLength(calculator{derivedClassName}.Length);
                        Add{derivedClassName}ContentSize(ref calculator, (global::{derivedClass})instance);
                        """)
                    .EndBlock();
            }
            
            sb.EndBlock()
                .AppendNewLine();
        }

        foreach (var type in types)
        {
            var className = GetClassNameFromFullName(type.FullName);
            var containsBaseClass = tree.HasBaseClass(type.FullName);

            sb.AppendIndentedLine($"public static void Calculate{className}Size(ref global::GProtobuf.Core.WriteSizeCalculator calculator, global::{type.FullName} obj)");
            sb.StartNewBlock();

            // For derived types, calculate ProtoInclude wrapper sizes
            if (containsBaseClass)
            {
                // Build inheritance chain from base to this type
                var inheritanceChain = new List<string>();
                var currentType = type.FullName;
                while (tree.TryGetBaseClassName(currentType, out var baseType))
                {
                    inheritanceChain.Insert(0, currentType);
                    currentType = baseType;
                }
                inheritanceChain.Insert(0, currentType); // Add the base type

                if (inheritanceChain.Count == 3)
                {
                    // Special case for 3-level hierarchy (A <- B <- C)
                    var classA = inheritanceChain[0];
                    var classB = inheritanceChain[1];
                    var classC = inheritanceChain[2];

                    var typeA = FindTypeByFullName(classA, tree);
                    var typeB = FindTypeByFullName(classB, tree);

                    var protoIncludeAtoB = typeA?.ProtoIncludes.FirstOrDefault(pi => pi.Type == classB);
                    var protoIncludeBtoC = typeB?.ProtoIncludes.FirstOrDefault(pi => pi.Type == classC);

                    if (protoIncludeAtoB != null && protoIncludeBtoC != null)
                    {
                        sb.AppendNewLine();
                        // Calculate tag 5 (B wrapper) size
                        WritePrecomputedTagForCalculator(sb, protoIncludeAtoB.FieldId, WireType.Len);

                        // Calculate B wrapper content inline (Tag10 + C size + C content + B content)
                        sb.AppendIndentedLine($"var tempCalc{protoIncludeAtoB.FieldId} = new global::GProtobuf.Core.WriteSizeCalculator();");
                        WritePrecomputedTagForCalculatorWithName(sb, $"tempCalc{protoIncludeAtoB.FieldId}", protoIncludeBtoC.FieldId, WireType.Len);

                        sb.AppendIndentedLine($"var tempCalcC = new global::GProtobuf.Core.WriteSizeCalculator();");
                        sb.AppendIndentedLine($"Calculate{GetClassNameFromFullName(classC)}ContentSize(ref tempCalcC, obj);");
                        sb.AppendIndentedLine($"tempCalc{protoIncludeAtoB.FieldId}.WriteVarUInt32((uint)tempCalcC.Length);");
                        sb.AppendIndentedLine($"tempCalc{protoIncludeAtoB.FieldId}.AddByteLength(tempCalcC.Length);");

                        sb.AppendIndentedLine($"Calculate{GetClassNameFromFullName(classB)}ContentSize(ref tempCalc{protoIncludeAtoB.FieldId}, obj);");
                        sb.AppendIndentedLine($"calculator.WriteVarUInt32((uint)tempCalc{protoIncludeAtoB.FieldId}.Length);");
                    }

                    // Add A fields to size
                    if (typeA?.ProtoMembers != null)
                    {
                        foreach (var member in typeA.ProtoMembers)
                        {
                            WriteProtoMemberSizeCalculator(sb, member);
                        }
                    }
                }
                else if (inheritanceChain.Count == 2)
                {
                    // Simple 2-level hierarchy (A <- B)
                    var classA = inheritanceChain[0];
                    var classB = inheritanceChain[1];

                    var typeA = FindTypeByFullName(classA, tree);
                    var protoInclude = typeA?.ProtoIncludes.FirstOrDefault(pi => pi.Type == classB);

                    if (protoInclude != null)
                    {
                        sb.AppendNewLine();
                        WritePrecomputedTagForCalculator(sb, protoInclude.FieldId, WireType.Len);
                        // Check if this type has its own fields
                        if (type.ProtoMembers.Count > 0)
                        {
                            // Calculate size of own fields
                            sb.AppendIndentedLine($"var tempCalcContent = new global::GProtobuf.Core.WriteSizeCalculator();");
                            sb.AppendIndentedLine($"SizeCalculators.Calculate{GetClassNameFromFullName(type.FullName)}ContentSize(ref tempCalcContent, obj);");
                            sb.AppendIndentedLine($"calculator.WriteVarUInt32((uint)tempCalcContent.Length);");
                        }
                        else
                        {
                            sb.AppendIndentedLine($"calculator.WriteVarInt32(0); // No fields inside final ProtoInclude");
                        }
                    }

                    // Add A fields to size
                    if (typeA?.ProtoMembers != null)
                    {
                        foreach (var member in typeA.ProtoMembers)
                        {
                            WriteProtoMemberSizeCalculator(sb, member);
                        }
                    }
                }
                else
                {
                    // Generic case for deeper hierarchies - TODO: implement if needed
                    sb.AppendIndentedLine($"// TODO: Handle hierarchy deeper than 3 levels");
                }
            }

            else
            {
                // Base type or non-inherited type

                // Calculate own ProtoIncludes (for switch on derived types)
                if (type.ProtoIncludes.Count > 0)
                {
                    sb.AppendNewLine();
                    sb.AppendIndentedLine("switch (obj)");
                    sb.StartNewBlock();
                    foreach (var include in type.ProtoIncludes)
                    {
                        var includedClassName = GetClassNameFromFullName(include.Type);
                        sb.AppendIndentedLine($"case global::{include.Type} obj1:");
                        sb.IncreaseIndent();
                        WritePrecomputedTagForCalculator(sb, include.FieldId, WireType.Len);
                        sb.AppendIndentedLine($"var lengthBefore{include.FieldId} = calculator.Length;");
                        sb.AppendIndentedLine($"Calculate{includedClassName}Size(ref calculator, obj1);");
                        sb.AppendIndentedLine($"var contentLength{include.FieldId} = calculator.Length - lengthBefore{include.FieldId};");
                        sb.AppendIndentedLine($"calculator.WriteVarUInt32((uint)contentLength{include.FieldId});");
                        sb.AppendIndentedLine("break;");
                        sb.DecreaseIndent();
                    }
                    sb.EndBlock();
                }

                // Calculate own fields
                foreach (var protoMember in type.ProtoMembers)
                {
                    WriteProtoMemberSizeCalculator(sb, protoMember);
                }
            }

            sb.EndBlock();
            sb.AppendNewLine();
        }

        sb.AppendNewLine();

        // Generate Content size calculators (without ProtoInclude wrapping)
        foreach (var type in types)
        {
            sb.AppendIndentedLine($"public static void Calculate{GetClassNameFromFullName(type.FullName)}ContentSize(ref global::GProtobuf.Core.WriteSizeCalculator calculator, global::{type.FullName} obj)");
            sb.StartNewBlock();

            // Calculate only content - no ProtoInclude wrapping, just OWN members (NOT inherited)
            // ContentSize methods should only include fields defined in THIS class
            foreach (var protoMember in type.ProtoMembers)
            {
                WriteProtoMemberSizeCalculator(sb, protoMember);
            }

            // DO NOT write inherited members in ContentSize methods
            // They are handled separately in the full Size methods

            sb.EndBlock();
            sb.AppendNewLine();
        }

        sb.EndBlock()
            .EndBlock();
        return sb.ToString();
    }
    
    private static void WriteProtoMemberSizeCalculator(StringBuilderWithIndent sb, ProtoMemberAttribute protoMember)
    {
        // Check if it's a nullable type
        bool isNullable = protoMember.IsNullable;
        var typeName = GetClassNameFromFullName(protoMember.Type);

        switch (typeName)
        {
            case "System.Int32":
            case "Int32":
            case "int":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if (obj.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    switch (protoMember.DataFormat)
                    {
                        case DataFormat.FixedSize:
                            WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.Fixed32b);
                            sb.AppendIndentedLine($"calculator.WriteFixedSizeInt32(obj.{protoMember.Name}.Value);");
                            break;
                        case DataFormat.ZigZag:
                            WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.VarInt);
                            sb.AppendIndentedLine($"calculator.WriteZigZag32(obj.{protoMember.Name}.Value);");
                            break;
                        default:
                            WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.VarInt);
                            sb.AppendIndentedLine($"calculator.WriteVarInt32(obj.{protoMember.Name}.Value);");
                            break;
                    }
                    sb.EndBlock();
                }
                else
                {
                    sb.AppendIndentedLine($"if (obj.{protoMember.Name} != 0)");
                    sb.StartNewBlock();
                    switch (protoMember.DataFormat)
                    {
                        case DataFormat.FixedSize:
                            WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.Fixed32b);
                            sb.AppendIndentedLine($"calculator.WriteFixedSizeInt32(obj.{protoMember.Name});");
                            break;
                        case DataFormat.ZigZag:
                            WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.VarInt);
                            sb.AppendIndentedLine($"calculator.WriteZigZag32(obj.{protoMember.Name});");
                            break;
                        default:
                            WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.VarInt);
                            sb.AppendIndentedLine($"calculator.WriteVarInt32(obj.{protoMember.Name});");
                            break;
                    }
                    sb.EndBlock();
                }
                break;
            
            case "uint":
            case "UInt32":
            case "System.UInt32":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if (obj.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.VarInt);
                    sb.AppendIndentedLine($"calculator.WriteUInt32(obj.{protoMember.Name}.Value);");
                }
                else
                {
                    sb.AppendIndentedLine($"if (obj.{protoMember.Name} != 0)");
                    sb.StartNewBlock();
                    WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.VarInt);
                    sb.AppendIndentedLine($"calculator.WriteUInt32(obj.{protoMember.Name});");
                }

                sb.EndBlock();
                break;

            case "bool":
            case "Boolean":
            case "System.Boolean":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if (obj.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.VarInt);
                    sb.AppendIndentedLine($"calculator.WriteBool(obj.{protoMember.Name}.Value);");
                    sb.EndBlock();
                }
                else
                {
                    WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.VarInt);
                    sb.AppendIndentedLine($"calculator.WriteBool(obj.{protoMember.Name});");
                }
                break;

            case "Double":
            case "double":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if (obj.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.Fixed64b);
                    sb.AppendIndentedLine($"calculator.WriteDouble(obj.{protoMember.Name}.Value);");
                    sb.EndBlock();
                }
                else
                {
                    WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.Fixed64b);
                    sb.AppendIndentedLine($"calculator.WriteDouble(obj.{protoMember.Name});");
                }
                break;

            case "Single":
            case "single":
            case "float":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if (obj.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.Fixed32b);
                    sb.AppendIndentedLine($"calculator.WriteFloat(obj.{protoMember.Name}.Value);");
                    sb.EndBlock();
                }
                else
                {
                    WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.Fixed32b);
                    sb.AppendIndentedLine($"calculator.WriteFloat(obj.{protoMember.Name});");
                }
                break;

            case "String":
            case "System.String":
            case "string":
                sb.AppendIndentedLine($"if (obj.{protoMember.Name} != null)");
                sb.StartNewBlock();
                WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.Len);
                sb.AppendIndentedLine($"calculator.WriteString(obj.{protoMember.Name});");
                sb.EndBlock();
                break;

            default:
                sb.AppendIndentedLine($"if (obj.{protoMember.Name} != null)");
                sb.StartNewBlock();
                WritePrecomputedTagForCalculator(sb, protoMember.FieldId, WireType.Len);
                sb.AppendIndentedLine($"var lengthBefore{protoMember.FieldId} = calculator.Length;");
                sb.AppendIndentedLine($"SizeCalculators.Calculate{typeName}Size(ref calculator, obj.{protoMember.Name});");
                sb.AppendIndentedLine($"var contentLength{protoMember.FieldId} = calculator.Length - lengthBefore{protoMember.FieldId};");
                sb.AppendIndentedLine($"calculator.WriteVarUInt32((uint)contentLength{protoMember.FieldId});");
                sb.EndBlock();
                break;
        }

        sb.AppendNewLine();
    }

    // Helper to generate optimized tag calculation for size calculator
    private static void WritePrecomputedTagForCalculator(StringBuilderWithIndent sb, int fieldId, WireType wireType)
    {
        var (tagBytes, tagLen) = PrecomputeTagBytes(fieldId, wireType);
        sb.AppendIndentedLine($"// Tag for field {fieldId}, {wireType}");
        sb.AppendIndentedLine($"calculator.AddByteLength({tagLen}); // Precomputed tag bytes: {tagBytes}");
    }
}