using System.Collections.Generic;
using System.Linq;

namespace GProtobuf.Generator;

internal static partial class CodeGenerator
{
    private static string GenerateSpanReaderClass(
        string namespaceName,
        IReadOnlyList<TypeDefinition> types,
        RefactoredObjectTree tree)
    {
        var sb = new StringBuilderWithIndent();

        sb.AppendMultiline(
            $"""
             // <auto-generated/>
             using GProtobuf.Core;
             using System;
             using System.Collections.Generic;
             using System.IO;
             using System.Buffers;
             using System.Text;

             namespace {namespaceName}.Readers
             """
        )
        .StartNewBlock()
        .AppendIndentedLine("public static class SpanReaders")
        .StartNewBlock();

        foreach (var type in types)
        {
            var className = GetClassNameFromFullName(type.FullName);
            var hasBaseClass = tree.HasBaseClass(type.FullName);
            
            sb.AppendIndentedLine($"public static global::{type.FullName} Read{className}(ref SpanReader reader)");
            sb.StartNewBlock();

            // Check if this type is part of inheritance hierarchy (has ProtoIncludes OR is referenced in base class ProtoInclude)
            bool isPartOfInheritanceHierarchy = type.ProtoIncludes.Count > 0 || hasBaseClass;

            if (!isPartOfInheritanceHierarchy)
            {
                // Simple case - no inheritance, just read content
                sb.AppendIndentedLine($"return Read{className}Content(ref reader);");
            }
            else
            {
                // Complex case - check for ProtoInclude first
                sb.AppendIndentedLine($"global::{type.FullName} result = default(global::{type.FullName});")
                    .AppendNewLine()
                    .AppendIndentedLine("while(!reader.IsEnd)")
                    .StartNewBlock()
                    .AppendIndentedLine("var (wireType, fieldId) = reader.ReadWireTypeAndFieldId();")
                    .AppendNewLine();

                WriteProtoIncludesInDeserializers(sb, type, tree);

                // In main Read methods, write ONLY ultimate base class fields
                // All other type-specific fields are handled in ReadXContent methods
                if (hasBaseClass)
                {
                    // This is a derived class - write only ultimate base class fields
                    var ultimateBaseClassName = FindUltimateBaseClass(type.FullName, tree);
                    var ultimateBaseType = FindTypeByFullName(ultimateBaseClassName, tree);

                    if (ultimateBaseType != null)
                    {
                        foreach (var baseMember in ultimateBaseType.ProtoMembers)
                        {
                            WriteProtoMember(sb, baseMember);
                        }
                    }
                }
                else
                {
                    // This is a base class - write own members
                    foreach (var protoMember in type.ProtoMembers)
                    {
                        WriteProtoMember(sb, protoMember);
                    }
                }

                sb.AppendIndentedLine("// default")
                    .AppendIndentedLine("reader.SkipField(wireType);")
                    .EndBlock()
                    .AppendIndentedLine("return result;");
            }
            sb.EndBlock();
            sb.AppendNewLine();
        }

        sb.AppendNewLine();

        // Generate Content reading methods
        foreach (var type in types)
        {
            var className = GetClassNameFromFullName(type.FullName);
            var hasBaseClass = tree.HasBaseClass(type.FullName);

            sb.AppendIndentedLine($"public static global::{type.FullName} Read{className}Content(ref SpanReader reader)");
            sb.StartNewBlock();

            // Check if this type is part of inheritance hierarchy (has ProtoIncludes OR is referenced in base class ProtoInclude)
            bool isPartOfInheritanceHierarchy = type.ProtoIncludes.Count > 0 || hasBaseClass;

            if (!isPartOfInheritanceHierarchy)
            {
                // Simple case - no inheritance, just create and fill instance
                sb.AppendIndentedLine($"global::{type.FullName} result = new global::{type.FullName}();")
                    .AppendNewLine()
                    .AppendIndentedLine("while(!reader.IsEnd)")
                    .StartNewBlock()
                    .AppendIndentedLine("var (wireType, fieldId) = reader.ReadWireTypeAndFieldId();")
                    .AppendNewLine();

                foreach (var protoMember in type.ProtoMembers)
                {
                    WriteProtoMember(sb, protoMember);
                }
            }
            else
            {
                // Complex case - check for ProtoInclude first and determine correct type
                // For non-abstract types, create instance immediately to handle cases with no type-specific fields
                if (type.IsAbstract)
                {
                    sb.AppendIndentedLine($"global::{type.FullName} result = default(global::{type.FullName});\r\n");
                }
                else
                {
                    sb.AppendIndentedLine($"global::{type.FullName} result = new global::{type.FullName}();\r\n");
                }

                sb.AppendIndentedLine("while(!reader.IsEnd)")
                    .StartNewBlock()
                    .AppendIndentedLine("var (wireType, fieldId) = reader.ReadWireTypeAndFieldId();")
                    .AppendNewLine();

                // Write own ProtoIncludes first (derived classes)
                if (type.ProtoIncludes.Count > 0)
                {
                    foreach (var protoInclude in type.ProtoIncludes)
                    {
                        sb.AppendIndentedLine($"if (fieldId == {protoInclude.FieldId})");
                        sb.StartNewBlock();
                        sb.AppendIndentedLine("var length = reader.ReadVarInt32();");
                        sb.AppendIndentedLine("var reader1 = new SpanReader(reader.GetSlice(length));");
                        sb.AppendIndentedLine($"result = Read{GetClassNameFromFullName(protoInclude.Type)}Content(ref reader1);");
                        sb.AppendIndentedLine("continue;");
                        sb.EndBlock();
                        sb.AppendNewLine();
                    }
                }

                // Only for abstract types, check if instance was created via ProtoInclude
                if (type.IsAbstract)
                {
                    sb.AppendIndentedLine("if (result == null)")
                        .StartNewBlock()
                        .AppendIndentedLine($"throw new InvalidOperationException($\"ProtoInclude field must be first for abstract type {type.FullName}. Is {{fieldId}} defined in ProtoInclude attributes?\");")
                        .EndBlock()
                        .AppendNewLine();
                }

                // Write fields specific to this type
                foreach (var protoMember in type.ProtoMembers)
                {
                    WriteProtoMember(sb, protoMember);
                }
            }

            sb.AppendIndentedLine("// default")
                .AppendIndentedLine("reader.SkipField(wireType);")
                .EndBlock()
                .AppendIndentedLine("return result;")
                .EndBlock()
                .AppendNewLine();
        }

        sb.EndBlock()
            .EndBlock();

        return sb.ToString();
    }

    private static void WriteProtoIncludesInDeserializers(
        StringBuilderWithIndent sb,
        TypeDefinition type,
        RefactoredObjectTree tree)
    {
        // Write own ProtoIncludes first (derived classes)
        if (type.ProtoIncludes.Count > 0)
        {
            foreach (var protoInclude in type.ProtoIncludes)
            {
                var className = GetClassNameFromFullName(protoInclude.Type);
                sb.AppendIndentedLine($"if (fieldId == {protoInclude.FieldId})")
                    .StartNewBlock()
                    .AppendIndentedLine("var length = reader.ReadVarInt32();")
                    .AppendIndentedLine("var reader1 = new SpanReader(reader.GetSlice(length));")
                    .AppendIndentedLine($"var contentResult = Read{className}Content(ref reader1);")
                    .AppendIndentedLine("result = contentResult;")
                    .AppendIndentedLine("continue;")
                    .EndBlock()
                    .AppendNewLine();
            }
        }

        // Generate all ProtoInclude field IDs in the entire inheritance hierarchy for this type
        WriteAllInheritanceFieldIds(sb, type.FullName, tree);
        
        sb.AppendIndentedLine("if (result == null)");
        sb.StartNewBlock();
        // If this type is referenced in base class ProtoInclude, it must have field ID at the beginning
        bool isInBaseProtoInclude = tree.HasBaseClass(type.FullName);
        if (type.IsAbstract || isInBaseProtoInclude)
        {
            string typeDescription = type.IsAbstract ? "abstract type" : "ProtoInclude type";
            sb.AppendIndentedLine($"throw new InvalidOperationException($\"ProtoInclude field must be first for {typeDescription} {type.FullName}. Is {{fieldId}} defined in ProtoInclude attributes?\");");
        }
        else
        {
            sb.AppendIndentedLine($"result = new global::{type.FullName}();");
        }
        sb.EndBlock();
        sb.AppendNewLine();
        // todo hybrid binary tree for many proto includes
    }
    
    private static void WriteAllInheritanceFieldIds(
        StringBuilderWithIndent sb,
        string typeName,
        RefactoredObjectTree tree)
    {
        var fieldIds = new List<(int FieldId, string CurrentTypeName)>();
        
        // Collect all field IDs in the inheritance chain
        CollectInheritanceFieldIds(typeName, fieldIds, tree);
        
        // Generate if statements for all field IDs
        foreach (var (fieldId, currentTypeName) in fieldIds)
        {
            sb.AppendIndentedLine($"if (fieldId == {fieldId})");
            sb.StartNewBlock();
            sb.AppendIndentedLine("var length = reader.ReadVarInt32();");
            sb.AppendIndentedLine("var reader1 = new SpanReader(reader.GetSlice(length));");
            sb.AppendIndentedLine($"var contentResult = Read{GetClassNameFromFullName(currentTypeName)}Content(ref reader1);");
            
            // Add type check and cast if this is not the exact type expected
            if (currentTypeName != typeName)
            {
                sb.AppendIndentedLine($"if (contentResult is global::{typeName} castResult)");
                sb.StartNewBlock();
                sb.AppendIndentedLine("result = castResult;");
                sb.AppendIndentedLine("continue;");
                sb.EndBlock();
                sb.AppendIndentedLine($"throw new InvalidOperationException($\"Expected type {typeName} but got {{contentResult?.GetType().Name ?? \"null\"}}\");");
            }
            else
            {
                sb.AppendIndentedLine("result = contentResult;");
                sb.AppendIndentedLine("continue;");
            }
            
            sb.EndBlock();
            sb.AppendNewLine();
        }
    }

    private static void CollectInheritanceFieldIds(
        string typeName,
        List<(int FieldId, string CurrentTypeName)> fieldIds,
        RefactoredObjectTree tree)
    {
        // Check if this type has a base class
        if (!tree.TryGetBaseClassName(typeName, out var baseClassName))
        {
            return;
        }

        // First collect field IDs from parent's hierarchy  
        CollectInheritanceFieldIds(baseClassName, fieldIds, tree);
            
        // Then add the field ID that references current type from its base class
        var baseType = FindTypeByFullName(baseClassName, tree);
        var protoInclude = baseType?.ProtoIncludes.FirstOrDefault(pi => pi.Type == typeName);
        if (protoInclude != null)
        {
            fieldIds.Add((protoInclude.FieldId, typeName));
        }
    }

    private static string FindUltimateBaseClass(string typeName, RefactoredObjectTree tree)
    {
        string currentType = typeName;
        string lastBaseType = currentType;
        
        // Walk up the inheritance chain to find the ultimate base class
        while (tree.TryGetBaseClassName(currentType, out var baseType))
        {
            lastBaseType = baseType;
            currentType = baseType;
        }
        
        return lastBaseType;
    }

    private static TypeDefinition? FindTypeByFullName(string fullName, RefactoredObjectTree tree)
    {
        foreach (var typeList in tree)
        {
            var type = typeList.Value.FirstOrDefault(t => t.FullName == fullName);
            if (type is not null)
                return type;
        }

        return null;
    }
    
    private static void WriteProtoMember(StringBuilderWithIndent sb, ProtoMemberAttribute protoMember)
    {
        var typeName = GetClassNameFromFullName(protoMember.Type);

        sb.AppendIndentedLine($"if (fieldId == {protoMember.FieldId})")
            .StartNewBlock();
        
        switch(typeName)
        {
            case "bool":
            case "Boolean":
            case "System.Boolean":
                sb.AppendIndentedLine($"result.{protoMember.Name} = reader.ReadBool(wireType);");
                break;

            case "System.Int32":
            case "Int32":
            case "int":
                switch (protoMember.DataFormat)
                {
                    case DataFormat.FixedSize:
                        sb.AppendIndentedLine($"result.{protoMember.Name} = reader.ReadFixedInt32();");
                        break;

                    case DataFormat.ZigZag:
                        sb.AppendIndentedLine($"result.{protoMember.Name} = reader.ReadZigZagVarInt32();");
                        break;

                    default:
                        sb.AppendIndentedLine($"result.{protoMember.Name} = reader.ReadVarInt32();");
                        break;
                }
                break;

            case "uint":
            case "UInt32":
            case "System.UInt32":
                sb.AppendIndentedLine($"result.{protoMember.Name} = reader.ReadUInt32(wireType);");
                break;


            case "float":
            case "Single":
            case "System.Single":
                sb.AppendIndentedLine($"result.{protoMember.Name} = reader.ReadFloat(wireType);");
                break;

            case "Double":
            case "double":
                sb.AppendIndentedLine($"result.{protoMember.Name} = reader.ReadDouble(wireType);");
                break;


            case "String":
            case "System.String":
            case "string":
                sb.AppendIndentedLine($"result.{protoMember.Name} = reader.ReadString(wireType);");
                break;

            default:

                sb.AppendIndentedLine("var length = reader.ReadVarInt32();")
                    .AppendIndentedLine("var reader1 = new SpanReader(reader.GetSlice(length));")
                    .AppendIndentedLine($"result.{protoMember.Name} = global::{protoMember.Namespace}.Serialization.SpanReaders.Read{typeName}(ref reader1);");
                break;
        }

        sb.AppendIndentedLine("continue;")
            .EndBlock()
            .AppendNewLine();
    }
}