using System.Collections.Generic;
using System.Linq;

namespace GProtobuf.Generator;

internal static partial class CodeGenerator
{
    private static string GenerateStreamWriterClass(
        string namespaceName,
        IReadOnlyList<TypeDefinition> types,
        RefactoredObjectTree tree)
    {
        var sb = new StringBuilderWithIndent();

        sb.AppendMultiline(
                $"""
                 // <auto-generated/>
                 using GProtobuf.Core;
                 using {namespaceName}.SizeCalculation;
                 using System;
                 using System.Collections.Generic;
                 using System.IO;
                 using System.Buffers;
                 using System.Text;

                 namespace {namespaceName}.Writers
                 """
            )
            .StartNewBlock();
        
        GenerateWriters(sb, tree, types, WriteTarget.Stream);

        sb.EndBlock();
        return sb.ToString();
    }
    
    private enum WriteTarget
    { 
        Stream,
        BufferWriter
    }

    private static void GenerateWriters(
        StringBuilderWithIndent sb,
        RefactoredObjectTree tree,
        IReadOnlyList<TypeDefinition> types,
        WriteTarget writeTarget)
    {
        var shortName = writeTarget switch
        {
            WriteTarget.Stream => "Stream",
            WriteTarget.BufferWriter => "Buffer",
            _ => ""
        };

        sb.AppendIndentedLine($"public static class {shortName}Writers");
        sb.StartNewBlock();

        foreach (var type in types)
        {
            var className = GetClassNameFromFullName(type.FullName);
            var hasBaseClass = tree.HasBaseClass(type.FullName);
            var derivedTypeNames = tree.GetDerivedClasses(type.FullName);
            
            // Write Content method
            sb
                .AppendIndentedLine($"private static void Write{className}Content(ref global::GProtobuf.Core.{shortName}Writer writer, global::{type.FullName} instance)")
                .StartNewBlock();

            foreach (var derivedTypeName in derivedTypeNames)
            {
                var derivedType = FindTypeByFullName(derivedTypeName, tree);
                var protoInclude = type.ProtoIncludes.FirstOrDefault(pi => pi.Type == derivedTypeName);
                if (protoInclude is null || derivedType is null)
                {
                    continue;
                }
                
                var derivedClassName = GetClassNameFromFullName(derivedType.FullName);

                sb.AppendIndentedLine($"if (instance is global::{derivedTypeName})")
                    .StartNewBlock();

                WritePrecomputedTag(sb, protoInclude.FieldId, WireType.Len);
                sb.AppendIndentedLine($"var calculator{protoInclude.FieldId} = new global::GProtobuf.Core.WriteSizeCalculator();")
                    .AppendNewLine()
                    .AppendIndentedLine($"SizeCalculators.Add{derivedClassName}ContentSize(ref calculator{protoInclude.FieldId}, (global::{derivedTypeName})instance);")
                    .AppendNewLine()
                    .AppendIndentedLine($"SizeCalculators.Calculate{derivedClassName}ContentSize(ref calculator{protoInclude.FieldId}, (global::{derivedTypeName})instance);")
                    .AppendIndentedLine($"writer.WriteVarUInt32((uint)calculator{protoInclude.FieldId}.Length);")
                    .AppendNewLine()
                    .AppendIndentedLine($"Write{derivedClassName}Content(ref writer, (global::{derivedTypeName})instance);");

                sb.EndBlock()
                    .AppendNewLine();
            }

            foreach (var member in type.ProtoMembers)
            {
                WriteProtoMemberSerializer(sb, member, writeTarget, shortName);
            }

            sb
                .EndBlock()
                .AppendNewLine();


            // Write method
            sb.AppendIndentedLine($"public static void Write{className}(ref global::GProtobuf.Core.{shortName}Writer writer, global::{type.FullName} instance)");
            sb.StartNewBlock();

            if (hasBaseClass)
            {
                var baseClassFullName = FindUltimateBaseClass(type.FullName, tree);
                var baseClassName = GetClassNameFromFullName(baseClassFullName);
                sb.AppendIndentedLine($"Write{baseClassName}(ref writer, instance);");
            }
            else
            {
                sb.AppendIndentedLine($"Write{className}Content(ref writer, instance);");           
            }

            sb.EndBlock();
            sb.AppendNewLine();
        }

        sb.EndBlock();

        sb.AppendNewLine();
    }
    
    // Helper to generate optimized tag write code
    private static void WritePrecomputedTag(StringBuilderWithIndent sb, int fieldId, WireType wireType)
    {
        var (tagBytes, tagLen) = PrecomputeTagBytes(fieldId, wireType);
        sb.AppendIndentedLine($"// Tag for field {fieldId}, {wireType}");
        if (tagLen == 1)
        {
            sb.AppendIndentedLine($"writer.WriteSingleByte({tagBytes});");
        }
        else
        {
            sb.AppendIndentedLine($"writer.WriteBytes(stackalloc byte[] {{ {tagBytes} }});");
        }
    }

    // Helper to generate optimized tag calculation for named size calculator (e.g., entryCalculator)
    private static void WritePrecomputedTagForCalculatorWithName(StringBuilderWithIndent sb, string calculatorName, int fieldId, WireType wireType)
    {
        var (tagBytes, tagLen) = PrecomputeTagBytes(fieldId, wireType);
        sb.AppendIndentedLine($"// Tag for field {fieldId}, {wireType}");
        sb.AppendIndentedLine($"{calculatorName}.AddByteLength({tagLen}); // Precomputed tag bytes: {tagBytes}");
    }

    // Helper method to precompute tag bytes at code generation time
    private static (string bytesString, int byteCount) PrecomputeTagBytes(int fieldId, WireType wireType)
    {
        uint tag = (uint)((fieldId << 3) | (int)wireType);
        var tagBytes = new List<byte>();
        
        // Encode as varint
        while (tag > 0x7F)
        {
            tagBytes.Add((byte)((tag & 0x7F) | 0x80));
            tag >>= 7;
        }
        tagBytes.Add((byte)tag);
        
        // Format as C# byte array literal
        string bytesString = string.Join(", ", tagBytes.Select(b => $"0x{b:X2}"));
        return (bytesString, tagBytes.Count);
    }
    
        private static void WriteProtoMemberSerializer(StringBuilderWithIndent sb, ProtoMemberAttribute protoMember, WriteTarget writeTarget, string writeTargetShortName)
    {
        WriteProtoMemberSerializerWithObject(sb, protoMember, "instance", writeTarget, writeTargetShortName);
    }
    
    private static void WriteProtoMemberSerializerWithObject(StringBuilderWithIndent sb, ProtoMemberAttribute protoMember, string objectName, WriteTarget writeTarget, string writeTargetShortName)
    {
        // Check if it's a nullable type
        bool isNullable = protoMember.IsNullable;
        var typeName = GetClassNameFromFullName(protoMember.Type);

        switch (typeName)
        {
            case "System.Int32":
            case "Int32":
            case "int":
                if (isNullable)
                {
                    // Nullable int? - write if not null (even if value is 0)
                    sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    switch (protoMember.DataFormat)
                    {
                        case DataFormat.FixedSize:
                            WritePrecomputedTag(sb, protoMember.FieldId, WireType.Fixed32b);
                            sb.AppendIndentedLine($"writer.WriteFixedSizeInt32({objectName}.{protoMember.Name}.Value);");
                            break;
                        case DataFormat.ZigZag:
                            WritePrecomputedTag(sb, protoMember.FieldId, WireType.VarInt);
                            sb.AppendIndentedLine($"writer.WriteZigZag32({objectName}.{protoMember.Name}.Value);");
                            break;
                        default:
                            WritePrecomputedTag(sb, protoMember.FieldId, WireType.VarInt);
                            sb.AppendIndentedLine($"writer.WriteVarInt32({objectName}.{protoMember.Name}.Value);");
                            break;
                    }
                    sb.EndBlock();
                }
                else
                {
                    // Non-nullable int - write if not 0
                    sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name} != 0)");
                    sb.StartNewBlock();
                    switch (protoMember.DataFormat)
                    {
                        case DataFormat.FixedSize:
                            WritePrecomputedTag(sb, protoMember.FieldId, WireType.Fixed32b);
                            sb.AppendIndentedLine($"writer.WriteFixedSizeInt32({objectName}.{protoMember.Name});");
                            break;
                        case DataFormat.ZigZag:
                            WritePrecomputedTag(sb, protoMember.FieldId, WireType.VarInt);
                            sb.AppendIndentedLine($"writer.WriteZigZag32({objectName}.{protoMember.Name});");
                            break;
                        default:
                            WritePrecomputedTag(sb, protoMember.FieldId, WireType.VarInt);
                            sb.AppendIndentedLine($"writer.WriteVarInt32({objectName}.{protoMember.Name});");
                            break;
                    }
                    sb.EndBlock();
                }
                break;

            case "bool":
            case "Boolean":
            case "System.Boolean":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    WritePrecomputedTag(sb, protoMember.FieldId, WireType.VarInt);
                    sb.AppendIndentedLine($"writer.WriteBool({objectName}.{protoMember.Name}.Value);");
                    sb.EndBlock();
                }
                else
                {
                    WritePrecomputedTag(sb, protoMember.FieldId, WireType.VarInt);
                    sb.AppendIndentedLine($"writer.WriteBool({objectName}.{protoMember.Name});");
                }
                break;

            case "uint":
            case "UInt32":
            case "System.UInt32":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    WritePrecomputedTag(sb, protoMember.FieldId, WireType.VarInt);
                    sb.AppendIndentedLine($"writer.WriteUInt32({objectName}.{protoMember.Name}.Value);");
                }
                else
                {
                    sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name} != 0)");
                    sb.StartNewBlock();
                    WritePrecomputedTag(sb, protoMember.FieldId, WireType.VarInt);
                    sb.AppendIndentedLine($"writer.WriteUInt32({objectName}.{protoMember.Name});");
                }

                sb.EndBlock();
                break;

            case "Double":
            case "double":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    WritePrecomputedTag(sb, protoMember.FieldId, WireType.Fixed64b);
                    sb.AppendIndentedLine($"writer.WriteDouble({objectName}.{protoMember.Name}.Value);");
                    sb.EndBlock();
                }
                else
                {
                    WritePrecomputedTag(sb, protoMember.FieldId, WireType.Fixed64b);
                    sb.AppendIndentedLine($"writer.WriteDouble({objectName}.{protoMember.Name});");
                }
                break;

            case "Single":
            case "single":
            case "float":
                if (isNullable)
                {
                    sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name}.HasValue)");
                    sb.StartNewBlock();
                    WritePrecomputedTag(sb, protoMember.FieldId, WireType.Fixed32b);
                    sb.AppendIndentedLine($"writer.WriteFloat({objectName}.{protoMember.Name}.Value);");
                    sb.EndBlock();
                }
                else
                {
                    WritePrecomputedTag(sb, protoMember.FieldId, WireType.Fixed32b);
                    sb.AppendIndentedLine($"writer.WriteFloat({objectName}.{protoMember.Name});");
                }
                break;

            case "String":
            case "System.String":
            case "string":
                sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name} != null)");
                sb.StartNewBlock();
                WritePrecomputedTag(sb, protoMember.FieldId, WireType.Len);
                sb.AppendIndentedLine($"writer.WriteString({objectName}.{protoMember.Name});");
                sb.EndBlock();
                break;

            default:
                sb.AppendIndentedLine($"if ({objectName}.{protoMember.Name} != null)");
                sb.StartNewBlock();
                sb.AppendIndentedLine($"var calculator{protoMember.FieldId} = new global::GProtobuf.Core.WriteSizeCalculator();");
                sb.AppendIndentedLine($"SizeCalculators.Calculate{typeName}Size(ref calculator{protoMember.FieldId}, {objectName}.{protoMember.Name});");
                WritePrecomputedTag(sb, protoMember.FieldId, WireType.Len);
                sb.AppendIndentedLine($"writer.WriteVarUInt32((uint)calculator{protoMember.FieldId}.Length);");
                sb.AppendIndentedLine($"{writeTargetShortName}Writers.Write{typeName}(ref writer, {objectName}.{protoMember.Name});");
                sb.EndBlock();
                break;
        }

        sb.AppendNewLine();
    }
}